const TG = 'https://api.telegram.org/bot';
const WORKER_URL = 'https://rmed-ai-bot.ructorr.workers.dev';
const SYNTX_URL = 'https://syntx.ai/welcome/zEIpwfrW';
const PAKOPAY_URL = 'https://t.me/pakopay_bot?start=1626444641';

const menu = {inline_keyboard:[
 [{text:'🎨 AI-фото',callback_data:'photo'},{text:'🎬 AI-видео',callback_data:'video'}],
 [{text:'🖼 Портфолио',callback_data:'portfolio'},{text:'💰 Услуги и цены',callback_data:'prices'}],
 [{text:'📝 Оставить заявку',callback_data:'lead'}],
 [{text:'⚡ SYNTX',url:SYNTX_URL},{text:'💳 Оплата зарубежных сервисов',url:PAKOPAY_URL}]
]};
const orderKeyboard={inline_keyboard:[[{text:'📝 Заказать',callback_data:'lead'}],[{text:'⬅️ Главное меню',callback_data:'home'}]]};
const adminMenu={inline_keyboard:[[{text:'➕ Добавить AI-фото',callback_data:'admin_add_photo'}],[{text:'➕ Добавить AI-видео',callback_data:'admin_add_video'}],[{text:'🗑 Очистить фото',callback_data:'admin_clear_photo'}],[{text:'🗑 Очистить видео',callback_data:'admin_clear_video'}],[{text:'👁 Посмотреть портфолио',callback_data:'portfolio'}]]};

async function api(env, method, body){const r=await fetch(`${TG}${env.BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok) console.log(method,await r.text());return r;}
async function send(env,chat_id,text,reply_markup){return api(env,'sendMessage',{chat_id,text,reply_markup});}
async function state(env,id){return await env.RMED_KV.get(`state:${id}`)||'';}
async function setState(env,id,v){v?await env.RMED_KV.put(`state:${id}`,v,{expirationTtl:86400}):await env.RMED_KV.delete(`state:${id}`);}
async function portfolio(env,kind){return JSON.parse(await env.RMED_KV.get(`portfolio:${kind}`)||'[]');}
async function savePortfolio(env,kind,x){await env.RMED_KV.put(`portfolio:${kind}`,JSON.stringify(x));}
async function showItems(env,chat,kind){let items=[];if(!kind||kind==='photo')items.push(...(await portfolio(env,'photo')).map(x=>['photo',x]));if(!kind||kind==='video')items.push(...(await portfolio(env,'video')).map(x=>['video',x]));if(!items.length)return send(env,chat,'Пока здесь нет загруженных работ. Скоро добавим примеры.',orderKeyboard);for(const [k,x] of items.slice(-12)){await api(env,k==='photo'?'sendPhoto':'sendVideo',{chat_id:chat,[k]:x.file_id,caption:x.caption||'RMED AI'});}return send(env,chat,'Хотите такой же проект?',orderKeyboard);}

async function callback(env,q){await api(env,'answerCallbackQuery',{callback_query_id:q.id});const d=q.data,chat=q.message.chat.id,uid=q.from.id;if(d==='home'){await setState(env,uid,'');return send(env,chat,'Главное меню:',menu);}if(d==='photo'){await send(env,chat,'🎨 AI-фото\n\n• рекламные изображения для бизнеса\n• персональные AI-фотосессии\n• карточки товаров и креативы\n• визуалы для соцсетей\n\nНиже — примеры работ.');return showItems(env,chat,'photo');}if(d==='video'){await send(env,chat,'🎬 AI-видео\n\n• рекламные AI-ролики\n• оживление фотографий\n• cinematic и viral-креативы\n• ролики для Reels / Shorts / TikTok\n\nНиже — примеры работ.');return showItems(env,chat,'video');}if(d==='portfolio'){await send(env,chat,'🖼 Портфолио RMED AI\n\nПоследние работы:');return showItems(env,chat);}if(d==='prices')return send(env,chat,'💰 Услуги RMED AI\n\n🎨 AI-фото — стоимость зависит от количества изображений и сложности задачи.\n\n🎬 AI-видео — стоимость зависит от длительности, сценария и сложности генерации.\n\n🏢 Для бизнеса — рекламные креативы и пакеты контента рассчитываются индивидуально.\n\nНажмите «Оставить заявку» — обсудим задачу и назовём точную стоимость.',orderKeyboard);if(d==='lead'){await setState(env,uid,'lead');return send(env,chat,'📝 Расскажите одним сообщением:\n\n1) что хотите сделать;\n2) фото или видео;\n3) ваш @username или телефон.\n\nЗаявка сразу придёт Руслану.');}if(String(uid)!==String(env.ADMIN_TELEGRAM_ID))return;if(d==='admin_add_photo'||d==='admin_add_video'){const k=d.endsWith('photo')?'photo':'video';await setState(env,uid,`upload:${k}`);return send(env,chat,k==='photo'?'📸 Отправь фотографию. Подпись можно добавить к сообщению.':'🎥 Отправь видео. Название/описание можно добавить в подписи.');}if(d==='admin_clear_photo'||d==='admin_clear_video'){const k=d.endsWith('photo')?'photo':'video';await savePortfolio(env,k,[]);return send(env,chat,`✅ Все ${k==='photo'?'AI-фото':'AI-видео'} удалены из портфолио.`,adminMenu);}}

async function message(env,m){const uid=m.from.id,chat=m.chat.id;if(m.text==='/start'){await setState(env,uid,'');return send(env,chat,'👋 Добро пожаловать в RMED AI.\n\nСоздаём AI-фото, AI-видео и рекламные креативы для бизнеса и соцсетей.\n\nВыберите нужный раздел:',menu);}if(m.text==='/admin'&&String(uid)===String(env.ADMIN_TELEGRAM_ID)){await setState(env,uid,'');const p=await portfolio(env,'photo'),v=await portfolio(env,'video');return send(env,chat,`⚙️ RMED AI — управление\n\nФото в портфолио: ${p.length}\nВидео в портфолио: ${v.length}\n\nЗдесь ты можешь добавлять работы прямо из Telegram.`,adminMenu);}const s=await state(env,uid);if(s.startsWith('upload:')&&String(uid)===String(env.ADMIN_TELEGRAM_ID)){const k=s.split(':')[1];let file_id;if(k==='photo'&&m.photo)file_id=m.photo[m.photo.length-1].file_id;if(k==='video'&&m.video)file_id=m.video.file_id;if(!file_id)return send(env,chat,'Нужен именно тот тип файла, который выбран в админ-меню.');const a=await portfolio(env,k);a.push({file_id,caption:m.caption||'RMED AI'});await savePortfolio(env,k,a);await setState(env,uid,'');return send(env,chat,`✅ ${k==='photo'?'Фото':'Видео'} добавлено. Всего: ${a.length}.`,adminMenu);}if(s==='lead'&&m.text){await setState(env,uid,'');const username=m.from.username?`@${m.from.username}`:'без username';if(env.ADMIN_TELEGRAM_ID)await send(env,env.ADMIN_TELEGRAM_ID,`🔥 Новая заявка RMED AI\n\nКлиент: ${[m.from.first_name,m.from.last_name].filter(Boolean).join(' ')}\nTelegram: ${username}\nID: ${uid}\n\n${m.text}`);return send(env,chat,'✅ Заявка отправлена. С вами свяжутся.',menu);}}

async function registerWebhook(env){
 if(!env.BOT_TOKEN||!env.WEBHOOK_SECRET)return;
 const r=await api(env,'setWebhook',{url:`${WORKER_URL}/telegram/webhook`,secret_token:env.WEBHOOK_SECRET,allowed_updates:['message','callback_query'],drop_pending_updates:false});
 console.log('setWebhook status',r.status);
}

export default {
 async fetch(request,env){const u=new URL(request.url);if(request.method==='GET')return Response.json({service:'RMED AI Bot',status:'ok',hosting:'Cloudflare Workers'});if(u.pathname!=='/telegram/webhook'||request.method!=='POST')return new Response('Not found',{status:404});if(request.headers.get('X-Telegram-Bot-Api-Secret-Token')!==env.WEBHOOK_SECRET)return new Response('Forbidden',{status:403});const update=await request.json();try{if(update.callback_query)await callback(env,update.callback_query);else if(update.message)await message(env,update.message);}catch(e){console.log(e.stack||e);}return Response.json({ok:true});},
 async scheduled(event,env,ctx){ctx.waitUntil(registerWebhook(env));}
};